<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_next_register</name>
   <tag></tag>
   <elementGuidId>6922a726-1c92-45d9-aff7-cf6d7281454a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btnRegister&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;btnRegister&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
