<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_fullname</name>
   <tag></tag>
   <elementGuidId>3b4db7fa-38da-4380-9d0c-24379ee96393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullname</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
