<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_next</name>
   <tag></tag>
   <elementGuidId>d23caecf-7783-49af-8d0c-40827386561f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#step2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;step2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
